name: Java CI with Gradle

# Trigger the workflow on every push or pull request to the 'main' branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # Run on the latest version of Ubuntu
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up JDK 11 (you can specify another version if required)
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    # Step 3: Cache Gradle dependencies to speed up future builds
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Step 4: Build the project and run tests
    - name: Build with Gradle
      run: ./gradlew build --no-daemon
